/**
 * FMPS Coordination Tool - Default Data & Configuration
 * This file contains dropdown options, default team members, and seed data.
 */

const DEFAULT_CONFIG = {
    eventTypes: [
        'Trade Show',
        'Trade Show + Partner Booth',
        'Trade Show + Speaking',
        'Trade Show + Industry Training',
        'Trade Show + Showcase',
        'Thought Leadership',
        'Local / Regional Event',
        'Webinar',
        'PEC Event',
        'Partner Onboarding',
        'Panduit ONE Roadshow',
        'Sales Training',
        'FMPS Sales Pitch',
        'Consultant Workshop',
        'Distributer Event',
        'Customer Visit',
        'Marketing Event',
        'Installation - Partner Meeting',
        'Hands-On Demo',
        'PTO - Vacation',
        'Media - Podcast, Interview',
        'Tabletop Display + Speaking',
        'Tabletop Display',
        'Partner Kickoff',
    ],
    teamMembers: [
        'Mahmoud',
        'Vince',
        'Chuks',
        'Bob',
        'Deb',
        'Joe',
        'Jeff Yeary',
        'Greg Batcho',
        'Kevin Hogan',
        'Pierre Bourdeau',
        'Glenn Miller',
        'Brett Swett',
        'Erick Carmona',
        'Mark Hwang',
    ],
    boothSizes: [
        '10 x 10',
        '10 x 20',
        '20 x 20',
        '20 x 30',
        '30 x 30',
        'Innovation Area',
        'Showcase',
        'Walking Only',
        'No Booth',
        'Partner Booth',
        'Counter Show',
        "6' Table",
        'Lab',
    ],
    displayTypes: [
        'Table Top',
        'Table Top + Bannerstand',
        'Demo (Tabletop) TSE DEMO-KIT',
        'Demo + Backdrop',
        'Demo + Kiosk + Backdrop',
        'Demo + Kiosk + Bannerstand',
        'Demo + Hands-on Kit 1',
        'Demo + Hands-on Kit 1 & 2',
        '4-Post Rack',
        '4-Post Rack + Bannerstand',
        '4-Post Rack + Backdrop',
        '4-Post Rack + Kiosk + Bannerstand',
        '4-Post Rack + Kiosk + Backdrop',
        '4-Post Rack + Demo (Tabletop)',
        'Tower - Main',
        'Tower - Main + Tabletop',
        'Tower - Main + Kiosk + Backdrop',
        'Towers - Both',
        'Inline',
        'Booth 20 x 30',
        'Virtual',
        'No Booth',
    ],
    boothProperty: [
        'Demo (Tabletop) TSE DEMO-KIT',
        'Demo (Tabletop) TSE DEMO-KIT + Bannerstand',
        'Demo + Backdrop',
        'Demo + Kiosk + Backdrop',
        'Demo + Kiosk + Bannerstand',
        'Demo + Hands-on Kit 1',
        'Demo + Hands-on Kit 1 & 2',
        '4-Post Rack',
        '4-Post Rack + Bannerstand',
        '4-Post Rack + Backdrop',
        '4-Post Rack + Kiosk + Bannerstand',
        '4-Post Rack + Kiosk + Backdrop',
        '4-Post Rack + Demo (Tabletop)',
        'Tower - Main',
        'Tower - Main + Tabletop',
        'Tower - Main + Kiosk + Backdrop',
        'Towers - Both',
        'Inline',
        'Virtual',
        'JECIC - Sandbox + PEC',
        'Cisco + Panduit Lab',
        'Bannerstand',
    ],
    regions: ['NA', 'LATAM', 'EMEA', 'APAC'],
    statuses: ['Confirmed', 'Placeholder', 'Pending', 'Done', 'Cancelled'],
    assetCategories: [
        'Mobile Demo',
        'Full Demo',
        'Rack Display',
        'Banner',
        'Kiosk',
        'Backdrop',
        'Bannerstand',
        'Tower',
        'Pelican Box',
        'Inline',
        'Hands-on Kit',
        '4-Post Rack',
    ],
};

// Seed assets from the Excel workbook
const SEED_ASSETS = [
    { id: 'a1', title: 'PXTC1ARA', partNumber: 'PXTC1ARA', category: 'Mobile Demo', totalQuantity: 2, location: '' },
    { id: 'a2', title: 'PXU1AJANNNXX', partNumber: 'PXU1AJANNNXX', category: 'Mobile Demo', totalQuantity: 3, location: '' },
    { id: 'a3', title: 'PXTM1AF', partNumber: 'PXTM1AF', category: 'Mobile Demo', totalQuantity: 9, location: '' },
    { id: 'a4', title: 'PXR1AJD', partNumber: 'PXR1AJD', category: 'Mobile Demo', totalQuantity: 3, location: '' },
    { id: 'a5', title: 'PXUP316AWH-UQ', partNumber: 'PXUP316AWH-UQ', category: 'Mobile Demo', totalQuantity: 1, location: '' },
    { id: 'a6', title: 'PXT515C19146', partNumber: 'PXT515C19146', category: 'Mobile Demo', totalQuantity: 3, location: '' },
    { id: 'a7', title: 'Mobile Demo Kit (laminated material)', partNumber: 'DEMO-MOBILE', category: 'Mobile Demo', totalQuantity: 1, location: '' },
    { id: 'a8', title: 'Rack Display (modified full display)', partNumber: 'RACK-01', category: 'Rack Display', totalQuantity: 1, location: '' },
    { id: 'a9', title: 'Full Demo Unit', partNumber: 'DEMO-FULL', category: 'Full Demo', totalQuantity: 1, location: '' },
    { id: 'a10', title: 'Yellow Pelican Box (Dummy - 1 Receiver, 1 Transmitter, patch panel, cable)', partNumber: 'PELICAN-01', category: 'Pelican Box', totalQuantity: 1, location: '' },
    { id: 'a11', title: 'FMPS Banner', partNumber: 'BANNER-01', category: 'Banner', totalQuantity: 1, location: '' },
];

// Empty initial state
const EMPTY_STATE = {
    events: [],
    assets: SEED_ASSETS,
    reservations: [],
    thoughtLeadership: [],
    config: DEFAULT_CONFIG,
    lastModified: new Date().toISOString(),
};
